### ISSUE TITLE
reverse bit file .vmem

### ISSUE THREAD

**Issue by luhen168** [DigitalDesign20232/RISCV32_ComplianceTestSuite#2]
linker is big edian , reverse bit when export file.vmem
![image](https://github.com/user-attachments/assets/ad4beaf5-6373-410b-a520-20d0039e42a1)

**Comment by Dark-GreenCat** [comment]
> linker is big edian , reverse bit when export file.vmem
> ![image](https://github.com/user-attachments/assets/ad4beaf5-6373-410b-a520-20d0039e42a1)
> 

@luhen168 Already fix in [Issue#4: fix nop to linker](https://github.com/DigitalDesign20232/RISCV32_ComplianceTestSuite/issues/4)
